.TH stawebg 1 "21 November 2013"
.SH NAME
stawebg \- static website generator
.SH SYNOPSIS
.\" copy from stawebg --help
\fBstawebg\fP [-h] [-t] [-o \fIoutput\fP] [-v] [\fIdirectory\fP]
.SH DESCRIPTION
stawebg is a static website generator. It supports arbitrary markup languages like markdown and generates the menu automatically.
.SH OPTIONS
.TP
\fB-h, --help\fP
show this help message and exit
.TP
\fB-t, --test\fP
write output to test directory
.TP
\fB-o \fIoutput\fP, --output \fIoutput\fP\fP
write output to this directory
.TP
\fB-v, --version\fP
show program's version number and exit
.SH SEE ALSO
markdown(1)
.SH BUGS
If you find bugs or have feature requests please use the issue tracker on github: https://github.com/svenhertle/stawebg/issues.
You can also write an email to the authors.
.SH AUTHOR
Sven Hertle (sven.hertle@googlemail.com)
.PP
Markus Teich (teichm@in.tum.de)
